#!/bin/bash

# Переменная $IMAGE_NAME добавляется в сборку, поэтому тег правильный.

echo "Строю работающий хук"
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
             --build-arg VCS_REF=`git rev-parse --short HEAD` \
             -t $IMAGE_NAME .
